### ISSUE TITLE
User / Permissions

### ISSUE THREAD

**Issue by wuffo** [PiotrCzapla/vscode-wordpress#4]
This may simply be my extreme naivete, so please forgive me if this is the case, but this codespace opens as user vscode. The /var/www/html directory and everything below it are owned by www-data. Is this the intent? User vscode has no permissions here, so how do I edit those files?
Thanks.

**Comment by PiotrCzapla** [comment]
No worries I'm glad that you found it working . This part indeed needs some clarification. 

I'm using this template to work on another repo and I link the code from  `/workspace/myplugin` to the right place inside of /var/www/html  (in cane of plugin ti will be `/var/www/html/wp-content/plugins/myplugin`). Then the linked code has by default right permissions.

The default umask create files so that others (including nobody) are able to read it, so apache should work fine on linked code.

If you just want to quickly play with the checked out Wordpress you can run: 
```
sudo chown vscode -R /var/www/
ln -s /var/www/html . 
``` 
This will let you edit files and show them in side of vscode.

Let me know if that works for you.

**Comment by PiotrCzapla** [comment]
The editor runs as vscode as it lets you then execute node packages. NPM complains quite heavily when run from root.
I didn't want to add "sudo" permissions to nobody so we ended up with a different user.

Besides I hate Wordpress changing it directory all the time so I tend to allow it only in some places like wp-content/wordfence  and disallow it in other places. Having a separate user mimics my production environments, which let's me play with permission schemes more easily.
